linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - bodyclose
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - prealloc
    - revive

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G107
      - G404
  staticcheck:
    checks:
      - all

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - bodyclose
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - revive
      text: "blank-imports"
    - linters:
        - gosec
      text: "G114"
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
